/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ID]
      ,[Code]
      ,[EngName]
      ,[ArbName]
      ,[ArbNameAbs]
      ,[NumTimes]
      ,[Remarks]
      ,[RegDate]
      ,[RegUserID]
      ,[RegComputerID]
      ,[CancelDate]
      ,[CancelUserID]
      ,[CancelComputerID]
      ,[Hours]
      ,[per]
  FROM [hmis].[dbo].[ServiceDosageFrequencies]